baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
sectionPagesMenu = 'main'

enableRobotsTXT = true

minify.disableXML = true
minify.minifyOutput = true

outputs.home = ['HTML']
